SAR/Controllers/OffensesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAR.Models;
using SAR.Models.EF;
using Newtonsoft.Json;
using PagedList;
using SAR.Support;

namespace SAR.Controllers
{
    public class OffensesController : Controller
    {
        private OffenseContext db = new OffenseContext();

        // GET: Offenses
        [Authorize]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.BrigadeSortParm = String.IsNullOrEmpty(sortOrder) ? "brigade_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.NumberSortParm = sortOrder == "Number" ? "number_desc" : "Number";
            ViewBag.PersonSortParm = sortOrder == "Person" ? "person_desc" : "Person";
            ViewBag.ReqSortParm = sortOrder == "Req" ? "req_desc" : "Req";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var offenses = from s in db.Offenses
                           select s;

            //Поиск по мастеру или текмту предписания
            if (!String.IsNullOrEmpty(searchString))
            {

                offenses = offenses.Where(s => s.Prescription.Contains(searchString)
                                       || s.ResponsiblePerson.Contains(searchString));
            }

            //Сортировка
            switch (sortOrder)
            {
                case "brigade_desc":
                    offenses = offenses.OrderByDescending(s => s.Brigade);
                    break;
                case "Date":
                    offenses = offenses.OrderBy(s => s.Date);
                    break;
                case "date_desc":
                    offenses = offenses.OrderByDescending(s => s.Date);
                    break;
                case "Number":
                    offenses = offenses.OrderBy(s => s.Number);
                    break;
                case "number_desc":
                    offenses = offenses.OrderByDescending(s => s.Number);
                    break;
                case "Person":
                    offenses = offenses.OrderBy(s => s.ResponsiblePerson);
                    break;
                case "person_desc":
                    offenses = offenses.OrderByDescending(s => s.ResponsiblePerson);
                    break;
                case "Req":
                    offenses = offenses.OrderBy(s => s.RequiredDate);
                    break;
                case "req_desc":
                    offenses = offenses.OrderByDescending(s => s.RequiredDate);
                    break;
                default:
                    offenses = offenses.OrderBy(s => s.Brigade);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(offenses.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult OffenseSearch(string name)
        {
            var alloffenses = db.Offenses.Where(a => a.ResponsiblePerson.Contains(name)).ToList();
            return PartialView(alloffenses);
        }
        // GET: Offenses
        [Authorize]
        public async Task<ActionResult> Stat()
        {
            Graphic graphic = new Graphic();
            
            ViewBag.DataPoints = JsonConvert.SerializeObject(graphic.Paint());
            ViewBag.DataPointsObject = JsonConvert.SerializeObject(graphic.PaintObject());
            ViewBag.DataPointsHeading = JsonConvert.SerializeObject(graphic.PaintHeading());
            ViewBag.DataPointsOpen = JsonConvert.SerializeObject(graphic.PaintOpenOffenses());
            ViewBag.DataPointsExpired = JsonConvert.SerializeObject(graphic.PaintExpiredOffenses());

            return View(await db.Offenses.ToListAsync());
        }

        // GET: Offenses/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offense offense = await db.Offenses.FindAsync(id);
            if (offense == null)
            {
                return HttpNotFound();
            }
            return View(offense);
        }

        // GET: Offenses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Offenses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Object,PersonIssued,Brigade,Number,Date,Heading,Prescription,Link,Action,ResponsiblePerson,RequiredDate,ActualDate,Status,Comment")] Offense offense)
        {
            if (ModelState.IsValid)
            {
                db.Offenses.Add(offense);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(offense);
        }

        // GET: Offenses/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offense offense = await db.Offenses.FindAsync(id);
            if (offense == null)
            {
                return HttpNotFound();
            }
            return View(offense);
        }

        // POST: Offenses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Object,PersonIssued,Brigade,Number,Date,Heading,Prescription,Link,Action,ResponsiblePerson,RequiredDate,ActualDate,Status,Comment")] Offense offense)
        {
            if (ModelState.IsValid)
            {
                db.Entry(offense).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(offense);
        }

        // GET: Offenses/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Offense offense = await db.Offenses.FindAsync(id);
            if (offense == null)
            {
                return HttpNotFound();
            }
            return View(offense);
        }

        // POST: Offenses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Offense offense = await db.Offenses.FindAsync(id);
            db.Offenses.Remove(offense);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

     
    }
}

SAR/Controllers/SettingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SAR.Models;
using SAR.Models.EF;

namespace SAR.Controllers
{
    public class SettingsController : Controller
    {
        private OffenseContext db = new OffenseContext();

        
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Index()
        {
            return View(await db.Settings.ToListAsync());
        }

        // GET: Settings/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Setting setting = await db.Settings.FindAsync(id);
            if (setting == null)
            {
                return HttpNotFound();
            }
            return View(setting);
        }

        // GET: Settings/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Settings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Adresses")] Setting setting)
        {
            if (ModelState.IsValid)
            {
                db.Settings.Add(setting);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(setting);
        }

        // GET: Settings/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Setting setting = await db.Settings.FindAsync(id);
            if (setting == null)
            {
                return HttpNotFound();
            }
            return View(setting);
        }

        // POST: Settings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Adresses")] Setting setting)
        {
            if (ModelState.IsValid)
            {
                db.Entry(setting).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(setting);
        }

        // GET: Settings/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Setting setting = await db.Settings.FindAsync(id);
            if (setting == null)
            {
                return HttpNotFound();
            }
            return View(setting);
        }

        // POST: Settings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Setting setting = await db.Settings.FindAsync(id);
            db.Settings.Remove(setting);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SAR/Views/Shared/_Layout - Account.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Система контроля предписаний</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {
            background-image: url('../../Content/Image/background_layout.jpg');
            background-size: cover;
        }
    </style>
</head>
<body>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ООО "ВПТ-Нефтемаш" Леонов В.В.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src='@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")'></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SAR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Система контроля предписаний</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        body {
            background-image: url('../../Content/Image/background_layout.jpg');
            background-size: cover;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="@Url.Action("Index", "Offenses")">Система контроля предписаний</a>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Offenses")">Реестр<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Stat", "Offenses")">Статистика</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Settings")">Настройки</a>
                </li>
                <li class="nav-item col-7">
                    
                </li>
                <li class="nav-item col justify-content-md-end">
                    <span class="text-light">@User.Identity.Name</span>
                </li>
                <li class="nav-item col justify-content-md-end">
                    <a class="nav-link" href="@Url.Action("Logout", "Account")">Выйти</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ООО "ВПТ-Нефтемаш" Леонов В.В.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src='@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")'></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>